### ISSUE TITLE
WLAN hosting and connectivity

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/spc-eyepi#19]
What's the easiest to add a new wifi network? (currently)

Feature: Pi should turn on its own wlan with a fixed ip if it couldn't connect to a know wifi network. Then the user can get on the pi's local wifi network and config it correctly for upload. 

This was implemented before... please review the code here: https://github.com/borevitzlab/picam and then email wekoch _ a t _ gmx.net with questions and cc me if something needs to be clarified.

**Comment by gdunstone** [comment]
This is nearly finished, it creates a WLAN if it can, but there is currently no method of scanning or connecting.

**Comment by gdunstone** [comment]
This is done.
