### ISSUE TITLE
Get eyepi's working reliably by ~Jan 7th

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/spc-eyepi#21]
Let's freeze existing feature additions and focus on getting the system to work reliably with the DSLRs.

Reliably means:
1. Captures full resolution JPG and RAW images at 1-min intervals (if possible; if that frame-rate is too high then 5-min intervals is fine)
2. Works for 7 days straight capturing images from 5am to 10pm **without requiring restart**
3. All images uploaded to designated folder(s) 
4. Camera and PI SD card doesn't get full because locally cached images (either on camera card or Pi) are deleted once successfully uploaded

**Comment by gdunstone** [comment]
There is currently one in gc036r
