### ISSUE TITLE
Preview capture

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/spc-eyepi#23]
* Hard to tell which camera is currently plugged into the pi. 

* To start, the landing page should draw a square or light up a green button or something for configs of each detected camera(s). 

* Also ideally one could hit the "take picture" button to make a camera take a picture to identify itself. 
* I know the shorter serial ID is available in the config page but that's covered by the camera tripod mount so not actually that accessible in practice.

**Comment by gdunstone** [comment]
I'm aware that the serial is covered.

I'll look into doing that.

On 23 January 2015 at 09:36, Tim Brown <notifications@github.com> wrote:

> Assigned #23 <https://github.com/borevitzlab/spc-eyepi/issues/23> to
> @gdunstone <https://github.com/gdunstone>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/borevitzlab/spc-eyepi/issues/23#event-223362442>.
>



--

**Comment by gdunstone** [comment]
Maybe we could tape the serial number for each camera to the top?
Like the raw one (thats all in hex)

**Comment by gdunstone** [comment]
Will add a take_preview function that waits for the camera.

**Comment by gdunstone** [comment]
need to wait for locking of the camera

**Comment by gdunstone** [comment]
The cameras now adequately lock themselves.
As of update 2.0.5-37 it is stable with camera locking.
