### ISSUE TITLE
UI improvements for the camera settings page

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/spc-eyepi#24]
![notes-on-io-changes](https://cloud.githubusercontent.com/assets/3067588/5869606/e4af4060-a30f-11e4-97b5-bd1cb0db9473.jpg)
see photo :)

**Comment by gdunstone** [comment]
The ftp settings ARENT global. Each camera has their own uploader.

On 23 January 2015 at 14:55, Tim Brown <notifications@github.com> wrote:

> Assigned #24 <https://github.com/borevitzlab/spc-eyepi/issues/24> to
> @gdunstone <https://github.com/gdunstone>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/borevitzlab/spc-eyepi/issues/24#event-223484695>.
>



--

**Comment by gdunstone** [comment]
And ill change the background writing.

On 24 January 2015 at 10:41, Gareth Dunstone <
freedom.2.the.leetle.people@gmail.com> wrote:

> The ftp settings ARENT global. Each camera has their own uploader.
>
> On 23 January 2015 at 14:55, Tim Brown <notifications@github.com> wrote:
>
>> Assigned #24 <https://github.com/borevitzlab/spc-eyepi/issues/24> to
>> @gdunstone <https://github.com/gdunstone>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/borevitzlab/spc-eyepi/issues/24#event-223484695>.
>>
>
>
>
> --
>
>


--

**Comment by gdunstone** [comment]
background writing changed.
advanced options hidden.

**Comment by gdunstone** [comment]
Cant put the long camera id up there because otherwise what to name other cameras that dont have an EOS serial number (like for any canon camera that isnt an EOS

**Comment by gdunstone** [comment]
closing and reopening as remaining issue.

Added feature to help the user with camera naming:
Config button in images page.
