### ISSUE TITLE
Commit current code to repo

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/spc-eyepi#26]
Keep changed code up to date on git hub

**Comment by gdunstone** [comment]
It is up to date now.
I wanted to test it.
Should hit the update button on the pis and change the settings to upload
webcam == true

On 16 March 2015 at 14:53, Tim Brown <notifications@github.com> wrote:

> Keep changed code up to date on git hub
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/borevitzlab/spc-eyepi/issues/26>.
>



--
