### ISSUE TITLE
Need better tracking of camera captures and if cameras are working

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/spc-eyepi#28]
for example GC03 and GC05 don't appear to be uploading images. But when I log into the pi's they say "capturing" and if I click on the "files" link and then "get list" there are no files listed. So how do I tell if the cameras are actually working and if so where the files or or what the upload problem is?

**Comment by gdunstone** [comment]
This is more than done; [here](https://github.com/borevitzlab/spc-eyepi/issues/27)
