### ISSUE TITLE
Cameras don't use off/on capture times

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/spc-eyepi#34]
Hi,

I'm pretty sure the pi in ch35 is configured to only capture from 2am to 11am but it appears to be captuyring 24/7. I think all the other cameras are doing this as well. Since we are already capturing 1 to 2GB per hour on 10 cameras this is a huge amount of useless data we'll have to go back and filter out. Server is already almost full (69/70TB!) so we need to reduce the amount of useless data we are collecting ASAP and it is way easier to do this ahead of time rather then after the fact.

please fix as soon as you can

thanks

**Comment by gdunstone** [comment]
This has been fixed.
