### ISSUE TITLE
Reset USB connection at the start of each run.

### ISSUE THREAD

**Issue by kdmurray91** [borevitzlab/spc-eyepi#4]
There are ways using the linux kernel to reset USB connections, that trick most devices into thinking they've been unplugged and replugged. This is often necessary to be able to "claim" the camera's connection with libgphoto. An example can be found here: 

http://marc.info/?l=linux-usb&m=121459435621262&w=2

However, I suspect (from some brief testing) that this will not be sufficient to reset the camera. Therefore, I'll look into getting a relay that resets the usb connection by doing an unplug-plug cycle either while waiting for the next timepoint, or at the script start. Not sure what will be more stable.

**Comment by gdunstone** [comment]
There is no need to reset the USB if using gphoto2 and subprocess as gphoto2 releases the connection to the camera.
Just need to make sure that the camera doesn't go to sleep (power save).
