### ISSUE TITLE
Use arcfour cipher in sftp

### ISSUE THREAD

**Issue by kdmurray91** [borevitzlab/spc-eyepi#7]
The capture process is limited by CPU, particularly in the encryption during the upload process. This isn't a high security application. Therefore, arcfour is probably the best cipher to use. 

You can pass a list of ciphers to a `sftp.Connection()` initialiser.  i.e.:

```python
       link = sftp.Connection(host=hostname, username=user, password=passwd, ciphers=['arcfour128',])
```

**Comment by gdunstone** [comment]
The default cipher is not too complex. And since threading the capture and uploads, it's non-blocking.
I'll look at changing the cipher shortly but I don't think that it will make much difference.
