### ISSUE TITLE
image upload status needs to update more reliably and frequently

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/spc-eyepi#71]
"last upload time" is frequently inaccurate on website needs to report accurately. if the uploads are really happening this randomly then that needs to be cleaned up enough that cameras upload within a reasonable time of capture and in a predictable way

thanks

**Comment by gdunstone** [comment]
This has been fixed/wontfix.
The uploader updates its status once its finished. otherwise it wasnt a successful upload.
