### ISSUE TITLE
pi temp/hum sensor reading improvements

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/spc-eyepi#72]
I spoke to someone at danforth who was using the same hardware as we are and he said if you repeat poll the sensor it gives a better reading (I only vaguely remember what he said so sorry if I'm not saying it correctly). I think the point was that if you ask it for a reading a few times in a row and then take the last reading it will be more consistent then we get now where it throws bad readings. The other option would be to remember the last few readings and drop the current one if it is out of range by some amount (or wait a sec and repoll if that fixes it). anyway, it would be nice if we could clean up the readings a bit since the bunk readings throw off the graphs pretty badly.

**Comment by gdunstone** [comment]
I do this.
